create global temporary table tt_av_rpt_distribucion (
  ano              number(4),
  mes              number(2),
  cod_area         char(1),
  desc_area        varchar2(30),
  banda            char(6),
  desc_banda       varchar2(60),
  basico_adm       number(13,2),
  nro_adm          number(4),
  basico_ope       number(13,2),
  nro_ope          number(4),
  basico_tot       number(13,2),
  nro_tot          number(4),
  imp_por_adm      number(13,2),
  imp_por_ope      number(13,2),
  adm_porc         number(6,3),
  adm_soles        number(13,2),
  adm_tope         number(13,2),
  ope_porc         number(6,3),
  ope_soles        number(13,2),
  ope_tope         number(13,2) ) ;
