create global temporary table tt_cnta_crrte_cts
(
codigo               char(8),
cod_trabajador       char(8),
nombre               varchar2(100),
cod_area             char(1),
desc_area            varchar2(30),
cod_seccion          char(3),
desc_seccion         varchar2(30),
cencos               char(10),
desc_cencos          varchar2(40),
fec_dpsto            date,
fec_calc             date,
tasa_interes         number(9,6),
imp_dpsto            number(11,2),
cts_dpsto_ant        number(11,2),
nuevo_saldo          number(11,2),
int_legal            number(11,2),
capital_interes      number(11,2),
nuevo_cap_int        number(11,2),
ret50_emp            number(11,2),
ret50_tra            number(11,2),
saldo_disp_ant       number(11,2),
nuevo_saldo_disp     number(11,2),
a_cta_cts            number(11,2),
saldo_disp_actual    number(11,2),
flag_control         char(1) ) ;
