create global temporary table tt_consulta_asistencia_cenc
( cod_area               char(1),
  desc_area              varchar2(40),
  cod_seccion            char(3),     
  desc_seccion           varchar2(40),
  cod_cencos             char(10),    
  desc_cencos            varchar2(40),
  cod_trabajador         char(8),
  nombres                varchar2(40),
  cod_carnet             char(10),     
  r_min_tardanza         number(11,2),
  r_hor_inasistencia     number(11,2),
  r_hor_sobretiempo      number(11,2),
  r_hor_trabajadas       number(11,2),
  u_min_tardanza         number(11,2),
  u_dia_inasistencia     number(11,2),
  u_hor_inasistencia     number(11,2),
  u_sob_sem_inglesa      number(11,2),
  u_sob_normal           number(11,2),
  u_sob_domingo          number(11,2),
  u_sob_feriado          number(11,2),
  u_gua_primera          number(11,2),
  u_gua_segunda          number(11,2),
  u_gua_tercera          number(11,2) ) ;
  
