create global temporary table tt_det_retencion_aportes (
 empresa_nom            varchar2(50),
 empresa_dir            char(30),
 ruc                    char(11),
 periodo                char(4),
 quiebre                char(2),
 codtra                 char(8),
 nombre_afp             varchar2(30),
 item                   number(4),
 nro_afp_ipss           char(15),
 paterno                varchar2(30),
 materno                varchar2(30),
 nombre1                varchar2(30),
 nombre2                varchar2(30),
 imp01                  number(13,2),
 imp02                  number(13,2),
 imp03                  number(13,2),
 imp04                  number(13,2),
 imp05                  number(13,2),
 imp06                  number(13,2),
 imp07                  number(13,2),
 imp08                  number(13,2),
 imp09                  number(13,2),
 imp10                  number(13,2),
 imp11                  number(13,2),
 imp12                  number(13,2),
 fec_cese               date ) ;
