create global temporary table tt_detalle_cuenta_corriente (
  flag_estado              char(1),
  cod_origen               char(2), 
  desc_origen              varchar2(50), 
  tipo_trabajador          char(3),
  desc_tipo_trabajador     varchar2(30), 
  cod_seccion              char(3), 
  desc_seccion             varchar2(30),
  cod_trabajador           char(8), 
  nombres                  varchar2(50), 
  tipo_doc                 char(4), 
  nro_doc                  char(10), 
  fec_prestamo             date,
  concepto                 char(4), 
  desc_concepto            varchar2(60), 
  cod_sit_prestamo         char(1),
  nro_cuotas               number(2), 
  cod_moneda               char(3), 
  imp_sol                  number(13,2), 
  des_sol                  number(13,2),
  sal_sol                  number(13,2), 
  imp_dol                  number(13,2), 
  des_dol                  number(13,2), 
  sal_dol                  number(13,2),
  nro_dscto                number(2), 
  fec_dscto                date, 
  imp_dscto_sol            number(13,2), 
  imp_dscto_dol            number(13,2) ) ;
