create global temporary table tt_liq_rpt_liquidaciones (
  tipo_tra              char(3), 
  desc_tiptra           varchar2(30), 
  cencos                char(10), 
  desc_cencos           varchar2(40),
  fec_desde             date, 
  fec_hasta             date, 
  nro_liquidacion       char(10), 
  cod_trabajador        char(8), 
  nombres               varchar2(60),
  fec_liquidacion       date, 
  ts_anos               number(2), 
  ts_meses              number(2), 
  ts_dias               number(2),
  imp_liq_bensoc        number(13,2), 
  imp_liq_remune        number(13,2), 
  imp_liq_total         number(13,2), 
  flag_forma_pago       char(1),
  imp_pagado            number(13,2), 
  imp_saldo             number(13,2), 
  imp_diferido          number(13,2), 
  imp_aplicado          number(13,2),
  flag_juicio           char(1), 
  flag_reposicion       char(1),
  imp_comp_adi          number(13,2),
  imp_ret_jud           number(13,2) ) ;
