create global temporary table tt_liq_rpt_fondo_retiro (
  cod_trabajador        char(8),
  cod_grupo             char(6),
  cod_sub_grupo         char(6),
  descripcion           varchar2(60),
  fec_desde             date,
  fec_hasta             date,
  te_anos               number(2),
  te_meses              number(2),
  te_dias               number(2),
  des_ano               number(4),
  des_mes               number(2),
  des_dia               number(2),
  inc_ano               number(4),
  inc_mes               number(2),
  inc_dia               number(2),
  concepto              char(4),
  desc_concepto         varchar2(60),
  importe               number(13,2),
  imp_ano               number(13,2),
  imp_mes               number(13,2),
  imp_dia               number(13,2),
  tot_ano               number(4),
  tot_mes               number(2),
  tot_dia               number(2) ) ;
