create global temporary table tt_retencion_aportes (
 cod_trabajador         char(8),
 nombre                 varchar2(60),
 dni_le                 char(8),
 fecha_ingreso          date,
 seccion                char(3),
 desc_seccion           varchar2(30),
 nombre_afp             varchar2(30),
 nro_afp                char(12),
 nro_ipss               char(15),
 nombre_mes             char(9),
 nro_mes                char(2),
 rem_asegurable         number(13,2),
 fdo_pensiones          number(13,2),
 seg_invalidez          number(13,2),
 apo_comision           number(13,2),
 aportes_onp            number(13,2),
 seg_agrario            number(13,2),
 seg_sctr               number(13,2) ) ;
